language: php

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2

before_install:
  - composer self-update --stable -n

install: travis_retry composer install --no-suggest --prefer-dist -n -o

script: vendor/bin/phpunit --coverage-clover ./clover.xml

after_success:
# Code coverage report
  - bash <(curl -s https://codecov.io/bash)
